# services:
#   fastapi-app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: fastapi-container
#     ports:
#       - "8001:8000"  # Маппинг порта хоста и контейнера
#     volumes:
#       - .:/app  # Монтируем текущую директорию внутрь контейнера (для разработки)
#     environment:
#       - ENVIRONMENT=development  # Пример переменных окружения
#     depends_on:
#       - mongodb  # Если используем MongoDB
#     networks:
#       - app-network 

#   mongodb:
#     image: mongo:latest
#     container_name: mongodb-container
#     ports:
#       - "${DATABASE_PORT}:${DATABASE_PORT}"
#     volumes:
#       - mongo-data:/data/db
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
#       MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
#     networks:
#       - app-network    
#       # - MONGO_URI=mongodb://mongodb:27017
    

#   mongo-express:
#     image: mongo-express:latest
#     container_name: mongo-express-db
#     environment:
#       ME_CONFIG_MONGODB_ENABLE_ADMIN: true
#       ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_USERNAME}
#       ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD}
#       ME_CONFIG_MONGODB_SERVER: mongo

#       ME_CONFIG_BASICAUTH_USERNAME: ${BASICAUTH_USERNAME}
#       ME_CONFIG_BASICAUTH_PASSWORD: ${BASICAUTH_PASSWORD}
#     ports:
#       - "8081:8081"
#     depends_on:
#       - mongodb

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   mongo-data:



# ---------------


services:
  fastapi-container:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: fastapi_container
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - mynetwork

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    networks:
      - mynetwork

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo

      ME_CONFIG_BASICAUTH_USERNAME: ${BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${BASICAUTH_PASSWORD}
    networks:
      - mynetwork
    depends_on:
      - mongo

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo_data:
